openapi: "3.0.0"

info:
  title: Angular
  version: "1.0"

paths:

  /:
    get:
      operationId: frontend.serve_root
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string

  /{filename}:
    get:
      operationId: frontend.serve_file
      parameters:
      - name: "filename"
        in: "path"
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string

  /assets/config/config.json:
    get:
      operationId: frontend.serve_config
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string