# This workflow will install Python dependencies and run tests

name: api-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: install requirements
        run: |
          cd backend
          pip install -r requirements.txt

      - name: run tests
        run: |
          cd backend
          mkdir data
          cd src
          python -m pytest --rootdir . --cov=. --cov-config=../config/.coveragerc --cov-report=xml:../coverage/coverage.xml
