name: docker-build
 
on:
  push:
    branches: [ ci-build ]
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup node.js
        uses: actions/setup-node@v1

      - name: install npm dependencies
        run: |
          cd frontend
          npm install
      - name: generate and build
        run: |
          cd frontend
          npm run generate:api
          npm run build

      - run: |
          cd frontend
          ls -la

      # - name: build image and push to gcr
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
      #     registry: docker.pkg.github.com
      #     repository: euleGIT/streetview-bingo/streetview-bingo
          # tag_with_ref: true

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: euleGIT/streetview-bingo
          registry: ghcr.io
          githubOrg: euleGIT
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }} 
