name: sonar-stats
on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: install requirements
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run coverage
        run: |
          mkdir config
          cd backend
          mkdir data
          cp ./config/test.config.yml ../config/test.config.yml
          python -m pytest --rootdir src --cov=src --cov-config=config/.coveragerc --cov-report=xml:coverage/coverage.xml
          cat ./coverage/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
