# This workflow will install Python dependencies and run tests

name: test-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r ./backend/requirements.txt
        pip install coverage
    - name: Run tests and coverage
      run: |
        cd backend
        coverage run -m pytest ./tests
        coverage report >> report.txt
        { echo "RESULT="; grep -oE '[^ ]+$' report.txt | tail -1 | sed 's/.$//'; } | tr "\n" " " >> $GITHUB_ENV
        echo ${{ env.RESULT }}
    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: be76ee17e9743cffe36884b6b9ffcb54
        filename: coverage.json
        label: api-coverage
        message: ${{ env.RESULT }}%
        color: red
